### ISSUE TITLE
Problem statement committed.

### ISSUE THREAD

**Issue by aoananp** [aoananp/cas741#1]
https://github.com/aoananp/cas741/blob/master/Doc/ProblemStatement/ProblemStatement.pdf

**Comment by smiths** [comment]
Hello @aoananp.  Your pdf file is actually empty.  Could you please recompile it?  Also, in the future, please phrase your issues, like issues.  That is, please assign me the task of reviewing your problem statement.  Very nice how you included the link to the problem statement explicitly in your issue.

**Comment by aoananp** [comment]
Hello, Professor @smiths. That's strange. I can open and see the file through the Desktop site. Do you happen to be using a mobile browser? It does not show up on mobile for me as well. Desktop (Chrome and Safari Desktop browsers) show up for me as well as my local Adobe Reader. -Paul

**Comment by smiths** [comment]
The preview in GitHub still doesn't work on my machine, but you are right that the file is there.  I have now had a look at your problem statement.  I have four suggestions:

1. Remove the part about the goal being a small step-size and the use of near infinitesimal steps.  Your implication that smaller steps reduce error is correct, but the way you present it is actually a bit misleading.

2. Include a clear statement about what you are implementing: a library for a family of ode solvers.

3. Include a few examples of where ode solvers are used, to provide motivation.

4. Clarify whether you are solving a single ode or a system of odes.

**Comment by aoananp** [comment]
Hello Dr. Smith,

Thank you for your suggestions - I have addressed them in the latest commit.

**Comment by smiths** [comment]
Coming together nicely.  Please address issue #2.  After that, I can probably close this issue.
