### ISSUE TITLE
CA document review: some typos

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#10]
* 3.1: 'families of known well-known...' (repetition of 'known')
* 5.2: 'amount by which a a ...' (repetition of 'a')
* 6: 'varying instance models', did you mean 'various instance models', or are the instance models varying/changing?
* Could specify the range of n (currently n = 0, 1, 2,..., ) to include the end, as 1n = 0, 1, ..., k-1' instead, to make it clear that k-1 is the last iteration to be performed
* σ is not included in the 2.2 table, but you put it in Appendix A instead, why?

**Comment by aoananp** [comment]
Addressed in Revision 1.
