### ISSUE TITLE
Remove SRS document from repo

### ISSUE THREAD

**Issue by smiths** [aoananp/cas741#11]
I'm assuming that your SRS document is no longer relevant in your repo.  I'm guessing that you have copied everything that is relevant to your CA document.  If that is the case, you should remove the SRS document to avoid confusion.  (The file will stay in version control, so you haven't actually lost any  information.)

**Comment by aoananp** [comment]
Removed remnants of SRS document in https://github.com/aoananp/cas741/commit/4f04a2d80907a632eb0349f826f833ea4f28d314.
