### ISSUE TITLE
Goal is not a small time step

### ISSUE THREAD

**Issue by smiths** [aoananp/cas741#2]
https://github.com/aoananp/cas741/blob/e28a8cacb5b6f719a176b0d2274d680cbed6f809/Doc/ProblemStatement/ProblemStatement.tex#L42

The goal is to solve the equation with an acceptable error, not to have a small time step.  Technically, if a large time step has acceptable error, that time step would be fine.

**Comment by aoananp** [comment]
Thank you, Dr. @smiths. Issue has been addressed in the latest commit.

**Comment by smiths** [comment]
Sounds good.  Your problem statement is approved.
