### ISSUE TITLE
TestPlan: 6.0.1 ODE String Parser - Maybe change input requirements

### ISSUE THREAD

**Issue by keshavd** [aoananp/cas741#25]
I wasn't too sure what these are doing becasue I'm unfamiliar with Matlab.

I'm going to assume that the user enters a string that represents the input function, and then your parser converts it to a Matlab function.

I don't know how different a matlab equation is versus what the user can potentially input. 

I assume the user would input` 'f(x,y) = ax^2 + by^2 -cx -dy - 1'.`

Is this very different than what Matlab takes as input? Maybe it would best to avoid the parser and make an input requirement that the equation is formatted in Matlab syntax.

**Comment by aoananp** [comment]
As the requirement states, the user will only input the right hand side of the equation: ax^2 + by^2 -cx -dy - 1'. The parsing functionality is handled by MATLAB.
