### ISSUE TITLE
TestPlan: 6.0.1 ODE String Parser - Maybe only one test

### ISSUE THREAD

**Issue by keshavd** [aoananp/cas741#26]
The only difference between the Trigonometry and simple parsing tests is the ability to parse triginomic identities right? 

I feel like the ability to parse the function versus parsing a couple key words (sin, tan etc) does not differ all that much and this may be unneccessary split. Maybe just do one parsing test?

**Comment by aoananp** [comment]
Yessir - parsing tests are done in conjunction with the functional requirements tests as MATLAB is used for parsing. 'Proof of use' is the argument used.
