### ISSUE TITLE
TestPlan: 4.4.5. Code Coverage Tool - Unclear

### ISSUE THREAD

**Issue by keshavd** [aoananp/cas741#28]
I think you could have specifically mentioned which tool you were going to use (like you did with the IDE being used for Static Analyzer). I get that you have to use commericial tools, I would've liked to know which ones they were.

I might be misinterpreting the meaning of the sentence but I also think you may run into issues with open-source developers when you claim that commercial code coverage tools have increased confidence lol

**Comment by aoananp** [comment]
Thank you - code coverage has been revisited and added to testing.
