### ISSUE TITLE
CA document review: numerical errors

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#3]
Section 5.1 says that the software can be implemented to find the most accurate method - how?
* Does the software output an error estimation?
* Will it test the different methods for you and give you the best?
Maybe you can rephrase this if it's not provided by the software.
Can you include the order of the error in the IMs? (eg, order(h^2))

**Comment by aoananp** [comment]
A NFR requirement has been added to provide a meaningful error estimation against MATLAB's ODE solver.
It will not test the different methods - rather, it will provide the option to the user as to which method he would like to use and he/she can compare the results via the error analysis tool.
This is addressed in Revision 1 of the CA.
