### ISSUE TITLE
CA document review: code inputs

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#4]
Some questions on the desired input to your code:
* Do you need only the input function to be continuous, or the input function and its derivative? (eg, A5)
* Can the input ODE be a symbolic function (parsing the string of the ODE in C2 sounds like symbolic is ok), or should the input be a function defined in whatever language the program runs in?
* Is the input of x_k restricted to a single value, or can an array be entered? A13 specifies 'a single dimension', which implies an array is ok, but most of the text sounds like you expect one value. (also maybe clarify what you mean by a single dimension - a 1D array has one dimension, but can have N elements)

**Comment by aoananp** [comment]
- I believe it should be both.
- The input ODE has to be of the form f(x, y) as x and y are the only variables being parsed.
- My apologies for the confusion. A13 has been removed. x_k shall be of a single value.

Addressed in Revision 1 of the CA.
