### ISSUE TITLE
CA document review: definitions

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#5]
You might consider adding 'differential equation', 'ordinary differential equation', 'first order differential equation' to your definitions section 5.2.

**Comment by aoananp** [comment]
- I believe it would be redundant as the reader has been constrained to someone who has knowledge of Undergraduate Calculus. Nevertheless, the definition of a Linear Ordinary Differential Equation has been included.

Addressed in Revision 1 of the CA.
