### ISSUE TITLE
CA document review: definition change

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#6]
I would change the definitions you give of 'linear' and 'continuous' functions. Currently the definition cites the behaviour of the function on the 'graph', which is then subjective on the method and coordinate system of plotting. These should be definitions which are less qualitative and subjective, and more mathematically formal. So for the continuous function, you might talk about the first derivative being defined at all points on the interval of interest (etc).

**Comment by aoananp** [comment]
- Thank you! I have revised the definition in Revision 1 of the CA.
