### ISSUE TITLE
CA document review: DD1 terminology

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#7]
You define y' in DD1 as the 'slope of the tangent line', but elsewhere you call it the first order ODE. 
* Is the 'slope of the tangent line' equivalent to the 'first order ODE'? I think of an ODE as something that needs to be solved, but the slope as a value at a point.
* Maybe it is equivalent, but using the different terminologies is a bit confusing, and is it necessary?

**Comment by aoananp** [comment]
I've added DD1 as a pre-amble into defining y' and dy/dx which is used in the Theoretical and Instance models.

I can further look into this, but for now I will close the issue.
