### ISSUE TITLE
CA document review: A2 rationale

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#8]
I don't understand the rationale you use for A2, why does choosing to solve first order ODEs give you a portable library?
Maybe you can drop this rationale, or even the assumption, as solving first order ODEs is the main purpose of the program and is covered in the GS.

**Comment by aoananp** [comment]
The rationale has been reworded to indicate the choice was made for practical and scope related reasons.

Addressed in Revision 1 of the CA.
