### ISSUE TITLE
CA document review: Explicit & non-linear

### ISSUE THREAD

**Issue by icbicket** [aoananp/cas741#9]
I can guess (sorry, don't remember a lot about non-linear ODEs & explicit forms, so I may be wrong on this) that for many non-linear first order ODEs, it would be difficult to write them in an explicit form. You don't exclude non-linear ODEs (A4), but you will be excluding those which cannot be written in an explicit form (A3). I'd have to check the conditions of allowing non-linear ODEs to be written in an explicit, rather than implicit form, but it seems like you're sneakily disqualifying a lot of (all?) non-linear ODEs with this. Maybe it's better to make this clear directly?
If non-linear ODEs can always be written explicitly, you can close this issue directly.

**Comment by aoananp** [comment]
I have constrained the program to only solve for explicit first order linear ODEs as the main intent was to demonstrate accuracy in the classical models of numerical approximations of ODE solutions.
